/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


export default function PirateOfficer(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('./Models/Players/PirateOfficer.gltf')
    return (
        <group {...props} rotation={[0, Math.PI,0]} ref={group} dispose={null}>
            <group position={[-0.17, 0.7, 0,]} >
                <mesh castShadow geometry={nodes.armLeft_2_1.geometry} material={nodes.armLeft_2_1.material} />
                <mesh castShadow geometry={nodes.armLeft_2_2.geometry} material={nodes.armLeft_2_2.material} />
                <mesh castShadow geometry={nodes.armLeft_2_3.geometry} material={nodes.armLeft_2_3.material} />
            </group>
            <group position={[0.17, 0.7, 0,]} >
                <mesh castShadow geometry={nodes.armRight_2_1.geometry} material={nodes.armRight_2_1.material} />
                <mesh castShadow geometry={nodes.armRight_2_2.geometry} material={nodes.armRight_2_2.material} />
                <mesh castShadow geometry={nodes.armRight_2_3.geometry} material={nodes.armRight_2_3.material} />
            </group>
            <group position={[0, 0.41, 0,]} >
                <mesh castShadow geometry={nodes.body_2_1.geometry} material={nodes.body_2_1.material} />
                <mesh castShadow geometry={nodes.body_2_2.geometry} material={nodes.body_2_2.material} />
                <mesh castShadow geometry={nodes.body_2_3.geometry} material={nodes.body_2_3.material} />
            </group>
            <group position={[0, 0.78, 0,]} >
                <mesh castShadow geometry={nodes.Group_85_1.geometry} material={nodes.Group_85_1.material} />
                <mesh castShadow geometry={nodes.Group_85_2.geometry} material={nodes.Group_85_2.material} />
                <group position={[0.23, 0.2, -0.11,]} rotation={[0.26, 0, 0,]} scale={[0.35, 0.35, 0.6,]} >
                    <mesh castShadow geometry={nodes.Group_85001_1.geometry} material={nodes.Group_85001_1.material} />
                    <mesh castShadow geometry={nodes.Group_85001_2.geometry} material={nodes.Group_85001_2.material} />
                </group>
            </group>
            <group position={[-0.16, 0.41, 0,]} >
                <mesh castShadow geometry={nodes.legLeft_2_1.geometry} material={nodes.legLeft_2_1.material} />
                <mesh castShadow geometry={nodes.legLeft_2_2.geometry} material={nodes.legLeft_2_2.material} />
            </group>
            <group position={[0.16, 0.41, 0,]} >
                <mesh castShadow geometry={nodes.legRight_2_1.geometry} material={nodes.legRight_2_1.material} />
                <mesh castShadow geometry={nodes.legRight_2_2.geometry} material={nodes.legRight_2_2.material} />
                <mesh castShadow geometry={nodes.legRight_2_3.geometry} material={nodes.legRight_2_3.material} />
            </group>
        </group>
    )
}

useGLTF.preload('./Models/Players/PirateOfficer.gltf')